apiVersion: v1
kind: Service
metadata:
  name: mysql-test
  labels:
    app: mysql-test
spec:
  type: NodePort
  ports:
    - port: 3306
      name: mysql-port
      nodePort: 30306
      protocol: TCP
  selector:
    app: mysql-test

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-test
spec:
  selector:
    matchLabels:
      app: mysql-test
  serviceName: "mysql-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "666666"
          ports:
            - containerPort: 3306
              name: mysql-test
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes: [ ReadWriteOnce ]
        storageClassName: nfs-ssd-mysql
        resources:
          requests:
            storage: 500Mi

