apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kpgs-pv
  labels:
    app: nfs-kpgs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-ssd
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /data/share
    server: 192.168.3.133
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-kpgs-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500M
  storageClassName: nfs-ssd
  selector:
    matchLabels:
      app: nfs-kpgs-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpgs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kpgs-app
  template:
    metadata:
      labels:
        app: kpgs-app
    spec:
      containers:
        - name: kpgs-docker
          image: k8s-docker:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/nfs"
              name: kpgs-storage
          ports:
            - name: http
              containerPort: 8080
      volumes:
        - name: kpgs-storage
          persistentVolumeClaim:
            claimName: nfs-kpgs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kpgs-app-svc
  labels:
    app: kpgs-app-deploy-svc
spec:
  type: NodePort
  selector:
    app: kpgs-app
  ports:
    - name: kpgs-app-deploy-svc-api
      port: 8080
      nodePort: 30899
---

# curl -X POST http://10.100.193.50:8089/api/v1/alerts -d '[{"labels":{"alertname":"test","pod":"kpgs-deployment-79c8764d65-bmnp2", "node":"k8sdev-virtual-machine"}}]'
apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: javadiag-operation
spec:
  processor:
    scriptRunner:
      script: |
        #!/usr/bin/env bash
        echo $1
        docker exec `docker ps | grep $1 | awk 'NR==1{print $1}'` jmap -dump:live,format=b,file=/nfs/$1-heap.bin 1
      #        kubectl exec -it kpgs-deployment-79c8764d65-bmnp2 -- jmap -dump:live,format=b,file=heap.bin 1
      # 这个需要 KubeDiag 官方支持才可以
      argKeys:
        - pod
      operationResultKey: "javadiag-result"
    timeoutSeconds: 60

---

apiVersion: diagnosis.kubediag.org/v1
kind: OperationSet
metadata:
  name: javadiag-operationset
spec:
  adjacencyList:
    - id: 0
      to:
        - 1
    - id: 1
      operation: javadiag-operation

---

apiVersion: diagnosis.kubediag.org/v1
kind: Trigger
metadata:
  name: javadiag-trigger
spec:
  operationSet: javadiag-operationset
  sourceTemplate:
    prometheusAlertTemplate:
      regexp:
        alertName: test21
      nodeNameReferenceLabel: node
      podNameReferenceLabel: pod
      parameterInjectionLabels:
        - node
        - pod