---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpgs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kpgs-app
  template:
    metadata:
      labels:
        app: kpgs-app
    spec:
      containers:
        - name: kpgs-docker
          image: k8s-docker:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kpgs-app-svc
  labels:
    app: kpgs-app-deploy-svc
spec:
  type: NodePort
  selector:
    app: kpgs-app
  ports:
    - name: kpgs-app-deploy-svc-api
      port: 8080
      nodePort: 30888