apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    app: pv-example
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /data/share
    server: 192.168.3.133