apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    app: test-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
#  storageClassName: nfs-storage
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /data/share
    server: 192.168.3.133