apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-world
  labels:
    app: k8s-hello-world
spec:
  type: NodePort      # 更改成 NodePort 类型，让Node外部有访问能力
  ports:
    - name: http
      port: 8080
      nodePort: 30888 # 此处定义POD的端口8080映射为Node的8888
  selector:
    app: k8s-hello-world