apiVersion: v1
kind: Service
metadata:
  name: k8s-hello-world
  labels:
    app: k8s-hello-world
spec:
  type: NodePort      # 更改成 NodePort 类型，让Node外部有访问能力
  ports:
    - name: http
      port: 8080
      nodePort: 8888 # 此处定义POD的端口8080映射为Node的8888
  selector:
    app: k8s-hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-hello-world
  template:
    metadata:
      labels:
        app: k8s-hello-world
    spec:
      containers:
        - name: k8s-hello-world
          image: k8s-docker:0.0.1-SNAPSHOT
          imagePullPolicy: Never  # 不要从远程仓库拉取
          ports:
            - name: http
              containerPort: 8080 # 此处定义POD暴露的端口