apiVersion: v1
kind: Service
metadata:
  name: tomcat-in-namespace
  namespace: pre-dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31002
  selector:
    tier: tomcat-dep
