apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: tomcat-dep
    matchExpressions:
      - {key: tier, operator: In, values: [tomcat-dep]}
  template:
    metadata:
      labels:
        app: tomcat-dep-demo
        tier: tomcat-dep
    spec:
      containers:
        - name: tomcat-dep-demo-container
          image: tomcat:8.5-jdk17-temurin-jammy
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080